#  ___       ___  __  ___  __        ___ 
# |__  |    |__  /  `  |  /  \ |\ | |__
# |    |___ |___ \__,  |  \__/ | \| |___
#  __             __   ___ 
# |__) |  | |    /__` |__  
# |    \__/ |___ .__/ |___   /\
#                           /  \
# __/\___  ____/\_____  ___/    \______
#        \/           \/  
#
#region config
console: "Console"
version: "0.8.3"
language: "en_us"
language-player: true
metrics: true
bungeecord: false
velocity: false
clusters: []
log-filter:
  - "Paper Async Command Builder"
  - "Caught previously unhandled exception :"
  - "Error received from Telegram GetUpdates Request"
  - "OkHttp TaskRunner"
database:
  type: SQLITE
  name: "flectonepulse"
  host: "localhost"
  port: "3306"
  user: "root"
  password: "1234"
  parameters: "?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8"
module:
  enable: true
#endregion config
