#  ___       ___  __  ___  __        ___ 
# |__  |    |__  /  `  |  /  \ |\ | |__
# |    |___ |___ \__,  |  \__/ | \| |___
#  __             __   ___ 
# |__) |  | |    /__` |__  
# |    \__/ |___ .__/ |___   /\
#                           /  \
# __/\___  ____/\_____  ___/    \______
#        \/           \/  
# 
#region config
console: "Console"
version: "1.5.0"
language: "en_us"
language-player: true
unregister-own-commands: false
metrics: true
bungeecord: false
velocity: false
clusters: []
fabric-disabled-commands:
  - "msg"
  - "kick"
  - "banlist"
  - "tell"
  - "w"
  - "me"
  - "pardon"
  - "ban"
log-filter:
  - "Paper Async Command Builder"
  - "Caught previously unhandled exception :"
  - "Error received from Telegram GetUpdates Request"
  - "OkHttp TaskRunner"
  - "Exception in thread \"ForkJoinPool"
  - "FlectonePulseDatabase - "
database:
  type: "SQLITE"
  name: "flectonepulse"
  host: "127.0.0.1"
  port: "3306"
  user: "root"
  password: "1234"
  parameters: "?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8"
module:
  enable: true
redis:
  enable: false
  host: "127.0.0.1"
  port: 6379
  ssl: false
  user: ""
  password: ""
editor:
  host: ""
  https: false
  port: 25566
#endregion config
