// @ts-nocheck
import * as __fd_glob_136 from "../src/pulse/content/docs/message/format/moderation/swear.mdx?collection=docs"
import * as __fd_glob_135 from "../src/pulse/content/docs/message/format/moderation/newbie.mdx?collection=docs"
import * as __fd_glob_134 from "../src/pulse/content/docs/message/format/moderation/index.mdx?collection=docs"
import * as __fd_glob_133 from "../src/pulse/content/docs/message/format/moderation/flood.mdx?collection=docs"
import * as __fd_glob_132 from "../src/pulse/content/docs/message/format/moderation/delete.mdx?collection=docs"
import * as __fd_glob_131 from "../src/pulse/content/docs/message/format/moderation/caps.mdx?collection=docs"
import * as __fd_glob_130 from "../src/pulse/content/docs/message/tab/playerlistname.mdx?collection=docs"
import * as __fd_glob_129 from "../src/pulse/content/docs/message/tab/index.mdx?collection=docs"
import * as __fd_glob_128 from "../src/pulse/content/docs/message/tab/header.mdx?collection=docs"
import * as __fd_glob_127 from "../src/pulse/content/docs/message/tab/footer.mdx?collection=docs"
import * as __fd_glob_126 from "../src/pulse/content/docs/message/status/version.mdx?collection=docs"
import * as __fd_glob_125 from "../src/pulse/content/docs/message/status/players.mdx?collection=docs"
import * as __fd_glob_124 from "../src/pulse/content/docs/message/status/motd.mdx?collection=docs"
import * as __fd_glob_123 from "../src/pulse/content/docs/message/status/index.mdx?collection=docs"
import * as __fd_glob_122 from "../src/pulse/content/docs/message/status/icon.mdx?collection=docs"
import * as __fd_glob_121 from "../src/pulse/content/docs/message/objective/tabname.mdx?collection=docs"
import * as __fd_glob_120 from "../src/pulse/content/docs/message/objective/index.mdx?collection=docs"
import * as __fd_glob_119 from "../src/pulse/content/docs/message/objective/belowname.mdx?collection=docs"
import * as __fd_glob_118 from "../src/pulse/content/docs/message/format/world.mdx?collection=docs"
import * as __fd_glob_117 from "../src/pulse/content/docs/message/format/scoreboard.mdx?collection=docs"
import * as __fd_glob_116 from "../src/pulse/content/docs/message/format/replacement.mdx?collection=docs"
import * as __fd_glob_115 from "../src/pulse/content/docs/message/format/questionanswer.mdx?collection=docs"
import * as __fd_glob_114 from "../src/pulse/content/docs/message/format/object.mdx?collection=docs"
import * as __fd_glob_113 from "../src/pulse/content/docs/message/format/names.mdx?collection=docs"
import * as __fd_glob_112 from "../src/pulse/content/docs/message/format/mention.mdx?collection=docs"
import * as __fd_glob_111 from "../src/pulse/content/docs/message/format/index.mdx?collection=docs"
import * as __fd_glob_110 from "../src/pulse/content/docs/message/format/fixation.mdx?collection=docs"
import * as __fd_glob_109 from "../src/pulse/content/docs/message/format/fcolor.mdx?collection=docs"
import * as __fd_glob_108 from "../src/pulse/content/docs/message/vanilla.mdx?collection=docs"
import * as __fd_glob_107 from "../src/pulse/content/docs/message/update.mdx?collection=docs"
import * as __fd_glob_106 from "../src/pulse/content/docs/message/translate.mdx?collection=docs"
import * as __fd_glob_105 from "../src/pulse/content/docs/message/sign.mdx?collection=docs"
import * as __fd_glob_104 from "../src/pulse/content/docs/message/sidebar.mdx?collection=docs"
import * as __fd_glob_103 from "../src/pulse/content/docs/message/rightclick.mdx?collection=docs"
import * as __fd_glob_102 from "../src/pulse/content/docs/message/quit.mdx?collection=docs"
import * as __fd_glob_101 from "../src/pulse/content/docs/message/join.mdx?collection=docs"
import * as __fd_glob_100 from "../src/pulse/content/docs/message/index.mdx?collection=docs"
import * as __fd_glob_99 from "../src/pulse/content/docs/message/greeting.mdx?collection=docs"
import * as __fd_glob_98 from "../src/pulse/content/docs/message/chat.mdx?collection=docs"
import * as __fd_glob_97 from "../src/pulse/content/docs/message/bubble.mdx?collection=docs"
import * as __fd_glob_96 from "../src/pulse/content/docs/message/brand.mdx?collection=docs"
import * as __fd_glob_95 from "../src/pulse/content/docs/message/bossbar.mdx?collection=docs"
import * as __fd_glob_94 from "../src/pulse/content/docs/message/book.mdx?collection=docs"
import * as __fd_glob_93 from "../src/pulse/content/docs/message/auto.mdx?collection=docs"
import * as __fd_glob_92 from "../src/pulse/content/docs/message/anvil.mdx?collection=docs"
import * as __fd_glob_91 from "../src/pulse/content/docs/message/afk.mdx?collection=docs"
import * as __fd_glob_90 from "../src/pulse/content/docs/integration/yandex.mdx?collection=docs"
import * as __fd_glob_89 from "../src/pulse/content/docs/integration/vault.mdx?collection=docs"
import * as __fd_glob_88 from "../src/pulse/content/docs/integration/twitch.mdx?collection=docs"
import * as __fd_glob_87 from "../src/pulse/content/docs/integration/triton.mdx?collection=docs"
import * as __fd_glob_86 from "../src/pulse/content/docs/integration/telegram.mdx?collection=docs"
import * as __fd_glob_85 from "../src/pulse/content/docs/integration/tab.mdx?collection=docs"
import * as __fd_glob_84 from "../src/pulse/content/docs/integration/supervanish.mdx?collection=docs"
import * as __fd_glob_83 from "../src/pulse/content/docs/integration/skinsrestorer.mdx?collection=docs"
import * as __fd_glob_82 from "../src/pulse/content/docs/integration/simplevoice.mdx?collection=docs"
import * as __fd_glob_81 from "../src/pulse/content/docs/integration/plasmovoice.mdx?collection=docs"
import * as __fd_glob_80 from "../src/pulse/content/docs/integration/placeholderapi.mdx?collection=docs"
import * as __fd_glob_79 from "../src/pulse/content/docs/integration/motd.mdx?collection=docs"
import * as __fd_glob_78 from "../src/pulse/content/docs/integration/minimotd.mdx?collection=docs"
import * as __fd_glob_77 from "../src/pulse/content/docs/integration/mineplaceholders.mdx?collection=docs"
import * as __fd_glob_76 from "../src/pulse/content/docs/integration/maintenance.mdx?collection=docs"
import * as __fd_glob_75 from "../src/pulse/content/docs/integration/luckperms.mdx?collection=docs"
import * as __fd_glob_74 from "../src/pulse/content/docs/integration/litebans.mdx?collection=docs"
import * as __fd_glob_73 from "../src/pulse/content/docs/integration/libertybans.mdx?collection=docs"
import * as __fd_glob_72 from "../src/pulse/content/docs/integration/itemsadder.mdx?collection=docs"
import * as __fd_glob_71 from "../src/pulse/content/docs/integration/interactivechat.mdx?collection=docs"
import * as __fd_glob_70 from "../src/pulse/content/docs/integration/index.mdx?collection=docs"
import * as __fd_glob_69 from "../src/pulse/content/docs/integration/geyser.mdx?collection=docs"
import * as __fd_glob_68 from "../src/pulse/content/docs/integration/floodgate.mdx?collection=docs"
import * as __fd_glob_67 from "../src/pulse/content/docs/integration/discord.mdx?collection=docs"
import * as __fd_glob_66 from "../src/pulse/content/docs/integration/deepl.mdx?collection=docs"
import * as __fd_glob_65 from "../src/pulse/content/docs/integration/advancedban.mdx?collection=docs"
import * as __fd_glob_64 from "../src/pulse/content/docs/config/proxy.mdx?collection=docs"
import * as __fd_glob_63 from "../src/pulse/content/docs/config/module.mdx?collection=docs"
import * as __fd_glob_62 from "../src/pulse/content/docs/config/metrics.mdx?collection=docs"
import * as __fd_glob_61 from "../src/pulse/content/docs/config/logger.mdx?collection=docs"
import * as __fd_glob_60 from "../src/pulse/content/docs/config/language.mdx?collection=docs"
import * as __fd_glob_59 from "../src/pulse/content/docs/config/index.mdx?collection=docs"
import * as __fd_glob_58 from "../src/pulse/content/docs/config/editor.mdx?collection=docs"
import * as __fd_glob_57 from "../src/pulse/content/docs/config/database.mdx?collection=docs"
import * as __fd_glob_56 from "../src/pulse/content/docs/config/command.mdx?collection=docs"
import * as __fd_glob_55 from "../src/pulse/content/docs/config/cache.mdx?collection=docs"
import * as __fd_glob_54 from "../src/pulse/content/docs/command/warnlist.mdx?collection=docs"
import * as __fd_glob_53 from "../src/pulse/content/docs/command/warn.mdx?collection=docs"
import * as __fd_glob_52 from "../src/pulse/content/docs/command/unwarn.mdx?collection=docs"
import * as __fd_glob_51 from "../src/pulse/content/docs/command/unmute.mdx?collection=docs"
import * as __fd_glob_50 from "../src/pulse/content/docs/command/unban.mdx?collection=docs"
import * as __fd_glob_49 from "../src/pulse/content/docs/command/try.mdx?collection=docs"
import * as __fd_glob_48 from "../src/pulse/content/docs/command/translateto.mdx?collection=docs"
import * as __fd_glob_47 from "../src/pulse/content/docs/command/toponline.mdx?collection=docs"
import * as __fd_glob_46 from "../src/pulse/content/docs/command/tictactoe.mdx?collection=docs"
import * as __fd_glob_45 from "../src/pulse/content/docs/command/tell.mdx?collection=docs"
import * as __fd_glob_44 from "../src/pulse/content/docs/command/symbol.mdx?collection=docs"
import * as __fd_glob_43 from "../src/pulse/content/docs/command/stream.mdx?collection=docs"
import * as __fd_glob_42 from "../src/pulse/content/docs/command/spy.mdx?collection=docs"
import * as __fd_glob_41 from "../src/pulse/content/docs/command/sprite.mdx?collection=docs"
import * as __fd_glob_40 from "../src/pulse/content/docs/command/rockpaperscissors.mdx?collection=docs"
import * as __fd_glob_39 from "../src/pulse/content/docs/command/reply.mdx?collection=docs"
import * as __fd_glob_38 from "../src/pulse/content/docs/command/poll.mdx?collection=docs"
import * as __fd_glob_37 from "../src/pulse/content/docs/command/ping.mdx?collection=docs"
import * as __fd_glob_36 from "../src/pulse/content/docs/command/online.mdx?collection=docs"
import * as __fd_glob_35 from "../src/pulse/content/docs/command/mutelist.mdx?collection=docs"
import * as __fd_glob_34 from "../src/pulse/content/docs/command/mute.mdx?collection=docs"
import * as __fd_glob_33 from "../src/pulse/content/docs/command/me.mdx?collection=docs"
import * as __fd_glob_32 from "../src/pulse/content/docs/command/maintenance.mdx?collection=docs"
import * as __fd_glob_31 from "../src/pulse/content/docs/command/mail.mdx?collection=docs"
import * as __fd_glob_30 from "../src/pulse/content/docs/command/kick.mdx?collection=docs"
import * as __fd_glob_29 from "../src/pulse/content/docs/command/index.mdx?collection=docs"
import * as __fd_glob_28 from "../src/pulse/content/docs/command/ignorelist.mdx?collection=docs"
import * as __fd_glob_27 from "../src/pulse/content/docs/command/ignore.mdx?collection=docs"
import * as __fd_glob_26 from "../src/pulse/content/docs/command/helper.mdx?collection=docs"
import * as __fd_glob_25 from "../src/pulse/content/docs/command/geolocate.mdx?collection=docs"
import * as __fd_glob_24 from "../src/pulse/content/docs/command/flectonepulse.mdx?collection=docs"
import * as __fd_glob_23 from "../src/pulse/content/docs/command/emit.mdx?collection=docs"
import * as __fd_glob_22 from "../src/pulse/content/docs/command/do.mdx?collection=docs"
import * as __fd_glob_21 from "../src/pulse/content/docs/command/dice.mdx?collection=docs"
import * as __fd_glob_20 from "../src/pulse/content/docs/command/deletemessage.mdx?collection=docs"
import * as __fd_glob_19 from "../src/pulse/content/docs/command/coin.mdx?collection=docs"
import * as __fd_glob_18 from "../src/pulse/content/docs/command/clearmail.mdx?collection=docs"
import * as __fd_glob_17 from "../src/pulse/content/docs/command/clearchat.mdx?collection=docs"
import * as __fd_glob_16 from "../src/pulse/content/docs/command/chatsetting.mdx?collection=docs"
import * as __fd_glob_15 from "../src/pulse/content/docs/command/chatcolor.mdx?collection=docs"
import * as __fd_glob_14 from "../src/pulse/content/docs/command/broadcast.mdx?collection=docs"
import * as __fd_glob_13 from "../src/pulse/content/docs/command/banlist.mdx?collection=docs"
import * as __fd_glob_12 from "../src/pulse/content/docs/command/ban.mdx?collection=docs"
import * as __fd_glob_11 from "../src/pulse/content/docs/command/ball.mdx?collection=docs"
import * as __fd_glob_10 from "../src/pulse/content/docs/command/anon.mdx?collection=docs"
import * as __fd_glob_9 from "../src/pulse/content/docs/command/afk.mdx?collection=docs"
import * as __fd_glob_8 from "../src/pulse/content/docs/index.mdx?collection=docs"
import * as __fd_glob_7 from "../src/pulse/content/docs/api.mdx?collection=docs"
import { default as __fd_glob_6 } from "../src/pulse/content/docs/message/objective/meta.json?collection=docs"
import { default as __fd_glob_5 } from "../src/pulse/content/docs/message/format/meta.json?collection=docs"
import { default as __fd_glob_4 } from "../src/pulse/content/docs/message/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../src/pulse/content/docs/integration/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../src/pulse/content/docs/config/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../src/pulse/content/docs/command/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../src/pulse/content/docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
} & {
  DocData: {
    docs: {
      /**
       * Last modified date of document file, obtained from version control.
       *
       */
      lastModified?: Date;
    },
  }
}>({"doc":{"passthroughs":["extractedReferences","lastModified"]}});

export const docs = await create.docs("docs", "src/pulse/content/docs", {"meta.json": __fd_glob_0, "command/meta.json": __fd_glob_1, "config/meta.json": __fd_glob_2, "integration/meta.json": __fd_glob_3, "message/meta.json": __fd_glob_4, "message/format/meta.json": __fd_glob_5, "message/objective/meta.json": __fd_glob_6, }, {"api.mdx": __fd_glob_7, "index.mdx": __fd_glob_8, "command/afk.mdx": __fd_glob_9, "command/anon.mdx": __fd_glob_10, "command/ball.mdx": __fd_glob_11, "command/ban.mdx": __fd_glob_12, "command/banlist.mdx": __fd_glob_13, "command/broadcast.mdx": __fd_glob_14, "command/chatcolor.mdx": __fd_glob_15, "command/chatsetting.mdx": __fd_glob_16, "command/clearchat.mdx": __fd_glob_17, "command/clearmail.mdx": __fd_glob_18, "command/coin.mdx": __fd_glob_19, "command/deletemessage.mdx": __fd_glob_20, "command/dice.mdx": __fd_glob_21, "command/do.mdx": __fd_glob_22, "command/emit.mdx": __fd_glob_23, "command/flectonepulse.mdx": __fd_glob_24, "command/geolocate.mdx": __fd_glob_25, "command/helper.mdx": __fd_glob_26, "command/ignore.mdx": __fd_glob_27, "command/ignorelist.mdx": __fd_glob_28, "command/index.mdx": __fd_glob_29, "command/kick.mdx": __fd_glob_30, "command/mail.mdx": __fd_glob_31, "command/maintenance.mdx": __fd_glob_32, "command/me.mdx": __fd_glob_33, "command/mute.mdx": __fd_glob_34, "command/mutelist.mdx": __fd_glob_35, "command/online.mdx": __fd_glob_36, "command/ping.mdx": __fd_glob_37, "command/poll.mdx": __fd_glob_38, "command/reply.mdx": __fd_glob_39, "command/rockpaperscissors.mdx": __fd_glob_40, "command/sprite.mdx": __fd_glob_41, "command/spy.mdx": __fd_glob_42, "command/stream.mdx": __fd_glob_43, "command/symbol.mdx": __fd_glob_44, "command/tell.mdx": __fd_glob_45, "command/tictactoe.mdx": __fd_glob_46, "command/toponline.mdx": __fd_glob_47, "command/translateto.mdx": __fd_glob_48, "command/try.mdx": __fd_glob_49, "command/unban.mdx": __fd_glob_50, "command/unmute.mdx": __fd_glob_51, "command/unwarn.mdx": __fd_glob_52, "command/warn.mdx": __fd_glob_53, "command/warnlist.mdx": __fd_glob_54, "config/cache.mdx": __fd_glob_55, "config/command.mdx": __fd_glob_56, "config/database.mdx": __fd_glob_57, "config/editor.mdx": __fd_glob_58, "config/index.mdx": __fd_glob_59, "config/language.mdx": __fd_glob_60, "config/logger.mdx": __fd_glob_61, "config/metrics.mdx": __fd_glob_62, "config/module.mdx": __fd_glob_63, "config/proxy.mdx": __fd_glob_64, "integration/advancedban.mdx": __fd_glob_65, "integration/deepl.mdx": __fd_glob_66, "integration/discord.mdx": __fd_glob_67, "integration/floodgate.mdx": __fd_glob_68, "integration/geyser.mdx": __fd_glob_69, "integration/index.mdx": __fd_glob_70, "integration/interactivechat.mdx": __fd_glob_71, "integration/itemsadder.mdx": __fd_glob_72, "integration/libertybans.mdx": __fd_glob_73, "integration/litebans.mdx": __fd_glob_74, "integration/luckperms.mdx": __fd_glob_75, "integration/maintenance.mdx": __fd_glob_76, "integration/mineplaceholders.mdx": __fd_glob_77, "integration/minimotd.mdx": __fd_glob_78, "integration/motd.mdx": __fd_glob_79, "integration/placeholderapi.mdx": __fd_glob_80, "integration/plasmovoice.mdx": __fd_glob_81, "integration/simplevoice.mdx": __fd_glob_82, "integration/skinsrestorer.mdx": __fd_glob_83, "integration/supervanish.mdx": __fd_glob_84, "integration/tab.mdx": __fd_glob_85, "integration/telegram.mdx": __fd_glob_86, "integration/triton.mdx": __fd_glob_87, "integration/twitch.mdx": __fd_glob_88, "integration/vault.mdx": __fd_glob_89, "integration/yandex.mdx": __fd_glob_90, "message/afk.mdx": __fd_glob_91, "message/anvil.mdx": __fd_glob_92, "message/auto.mdx": __fd_glob_93, "message/book.mdx": __fd_glob_94, "message/bossbar.mdx": __fd_glob_95, "message/brand.mdx": __fd_glob_96, "message/bubble.mdx": __fd_glob_97, "message/chat.mdx": __fd_glob_98, "message/greeting.mdx": __fd_glob_99, "message/index.mdx": __fd_glob_100, "message/join.mdx": __fd_glob_101, "message/quit.mdx": __fd_glob_102, "message/rightclick.mdx": __fd_glob_103, "message/sidebar.mdx": __fd_glob_104, "message/sign.mdx": __fd_glob_105, "message/translate.mdx": __fd_glob_106, "message/update.mdx": __fd_glob_107, "message/vanilla.mdx": __fd_glob_108, "message/format/fcolor.mdx": __fd_glob_109, "message/format/fixation.mdx": __fd_glob_110, "message/format/index.mdx": __fd_glob_111, "message/format/mention.mdx": __fd_glob_112, "message/format/names.mdx": __fd_glob_113, "message/format/object.mdx": __fd_glob_114, "message/format/questionanswer.mdx": __fd_glob_115, "message/format/replacement.mdx": __fd_glob_116, "message/format/scoreboard.mdx": __fd_glob_117, "message/format/world.mdx": __fd_glob_118, "message/objective/belowname.mdx": __fd_glob_119, "message/objective/index.mdx": __fd_glob_120, "message/objective/tabname.mdx": __fd_glob_121, "message/status/icon.mdx": __fd_glob_122, "message/status/index.mdx": __fd_glob_123, "message/status/motd.mdx": __fd_glob_124, "message/status/players.mdx": __fd_glob_125, "message/status/version.mdx": __fd_glob_126, "message/tab/footer.mdx": __fd_glob_127, "message/tab/header.mdx": __fd_glob_128, "message/tab/index.mdx": __fd_glob_129, "message/tab/playerlistname.mdx": __fd_glob_130, "message/format/moderation/caps.mdx": __fd_glob_131, "message/format/moderation/delete.mdx": __fd_glob_132, "message/format/moderation/flood.mdx": __fd_glob_133, "message/format/moderation/index.mdx": __fd_glob_134, "message/format/moderation/newbie.mdx": __fd_glob_135, "message/format/moderation/swear.mdx": __fd_glob_136, });